DROP TABLE public.users CASCADE;
DROP TABLE public.employee CASCADE;
DROP TABLE public."location" CASCADE;
DROP TABLE public.classcatalogue CASCADE;
DROP TABLE public.useractivity CASCADE;
DROP TABLE public.membership CASCADE;
DROP TABLE public.checkinactivity CASCADE;
DROP TABLE public."class" CASCADE;
DROP TABLE public.device CASCADE;