// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
)

type Querier interface {
	CreateActivityRecords(ctx context.Context, arg CreateActivityRecordsParams) (Activityrecord, error)
	CreateCheckinActivity(ctx context.Context, arg CreateCheckinActivityParams) (Checkinactivity, error)
	CreateCheckinRecords(ctx context.Context, arg CreateCheckinRecordsParams) (Checkinrecord, error)
	CreateClass(ctx context.Context, arg CreateClassParams) (Class, error)
	CreateClassCatalogue(ctx context.Context, arg CreateClassCatalogueParams) (Classcatalogue, error)
	CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error)
	CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error)
	CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error)
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error)
	CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserActivity(ctx context.Context, arg CreateUserActivityParams) (Useractivity, error)
	GetAllClasses(ctx context.Context) (Class, error)
	GetAllClassesOfferedAndAttendees(ctx context.Context) ([]GetAllClassesOfferedAndAttendeesRow, error)
	GetAllClassesOfferedAndAttendeesPerWeek(ctx context.Context) ([]GetAllClassesOfferedAndAttendeesPerWeekRow, error)
	GetAllDevices(ctx context.Context) ([]Device, error)
	GetAllLocations(ctx context.Context) ([]Location, error)
	GetAllSchedules(ctx context.Context) ([]Schedule, error)
	GetAllTopAttendedClass(ctx context.Context) ([]GetAllTopAttendedClassRow, error)
	GetAverageVisitorsPerHourWeekdays(ctx context.Context) ([]GetAverageVisitorsPerHourWeekdaysRow, error)
	GetAverageVisitorsPerHourWeekends(ctx context.Context) ([]GetAverageVisitorsPerHourWeekendsRow, error)
	GetBusiestTimeByHourAndDayOfWeek(ctx context.Context) ([]GetBusiestTimeByHourAndDayOfWeekRow, error)
	GetCheckinActivity(ctx context.Context, userid int64) ([]Checkinactivity, error)
	GetClass(ctx context.Context, id int64) (Class, error)
	GetClassEnrolment(ctx context.Context, courseid int64) ([]int64, error)
	GetClassRevenueGenerateByLocation(ctx context.Context) ([]GetClassRevenueGenerateByLocationRow, error)
	GetClassesOfferedAndAttendees(ctx context.Context, locationid int64) ([]GetClassesOfferedAndAttendeesRow, error)
	GetClassesOfferedAndAttendeesPerWeek(ctx context.Context, locationid int64) ([]GetClassesOfferedAndAttendeesPerWeekRow, error)
	GetDailyNewMemberEnrolments(ctx context.Context) ([]GetDailyNewMemberEnrolmentsRow, error)
	GetDayWiseActivity(ctx context.Context, userid int64) ([]GetDayWiseActivityRow, error)
	GetDevice(ctx context.Context, id int64) (Device, error)
	GetEmployee(ctx context.Context, name string) (Employee, error)
	GetEmployeeFromEmail(ctx context.Context, email string) (Employee, error)
	GetHoursSpentInGymByDay(ctx context.Context) ([]GetHoursSpentInGymByDayRow, error)
	GetKMostFrequentMembers(ctx context.Context, limit int32) ([]GetKMostFrequentMembersRow, error)
	GetLatestActivityRecord(ctx context.Context, userid int64) (Activityrecord, error)
	GetLatestCheckinRecord(ctx context.Context, userid int64) (Checkinrecord, error)
	GetLocation(ctx context.Context, id int64) (Location, error)
	GetMembership(ctx context.Context, userid int64) (Membership, error)
	GetMembershipCountsByType(ctx context.Context) ([]GetMembershipCountsByTypeRow, error)
	GetMostPopularHourForClassesOnWeekdays(ctx context.Context) ([]GetMostPopularHourForClassesOnWeekdaysRow, error)
	GetMostPopularHourForClassesOnWeekends(ctx context.Context) ([]GetMostPopularHourForClassesOnWeekendsRow, error)
	GetPastWorkoutData(ctx context.Context, arg GetPastWorkoutDataParams) ([]GetPastWorkoutDataRow, error)
	GetRevenueGenerateByMemberships(ctx context.Context) ([]int64, error)
	GetSchedule(ctx context.Context, id int64) (Schedule, error)
	GetUser(ctx context.Context, name string) (User, error)
	GetUserActivity(ctx context.Context, userid int64) ([]Useractivity, error)
	GetUserClass(ctx context.Context, userid int64) ([]Classcatalogue, error)
	GetUserFromEmail(ctx context.Context, email string) (User, error)
}

var _ Querier = (*Queries)(nil)
