// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: useractivity.sql

package db

import (
	"context"
	"time"
)

const createUserActivity = `-- name: CreateUserActivity :one
INSERT INTO useractivity
("start" ,"end" ,userid,deviceid,locationid)
VALUES
    ($1,$2,$3,$4,$5) RETURNING id, start, "end", userid, deviceid, locationid
`

type CreateUserActivityParams struct {
	Start      time.Time `json:"start"`
	End        time.Time `json:"end"`
	Userid     int64     `json:"userid"`
	Deviceid   int64     `json:"deviceid"`
	Locationid int64     `json:"locationid"`
}

func (q *Queries) CreateUserActivity(ctx context.Context, arg CreateUserActivityParams) (Useractivity, error) {
	row := q.db.QueryRowContext(ctx, createUserActivity,
		arg.Start,
		arg.End,
		arg.Userid,
		arg.Deviceid,
		arg.Locationid,
	)
	var i Useractivity
	err := row.Scan(
		&i.ID,
		&i.Start,
		&i.End,
		&i.Userid,
		&i.Deviceid,
		&i.Locationid,
	)
	return i, err
}

const getUserActivity = `-- name: GetUserActivity :many
SELECT id, start, "end", userid, deviceid, locationid FROM useractivity
WHERE userid = $1
`

func (q *Queries) GetUserActivity(ctx context.Context, userid int64) ([]Useractivity, error) {
	rows, err := q.db.QueryContext(ctx, getUserActivity, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Useractivity{}
	for rows.Next() {
		var i Useractivity
		if err := rows.Scan(
			&i.ID,
			&i.Start,
			&i.End,
			&i.Userid,
			&i.Deviceid,
			&i.Locationid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
