// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/checkinActivity": {
            "get": {
                "description": "Get CheckinActivity from  data in Db.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "checkinActivity"
                ],
                "summary": "Get CheckinActivity",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "userid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.checkinActivityResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create CheckinActivity data in Db.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "checkinActivity"
                ],
                "summary": "Create CheckinActivity",
                "parameters": [
                    {
                        "description": "Create Checkin Activity",
                        "name": "device",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.createCheckinActivityRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.checkinActivityResponse"
                        }
                    }
                }
            }
        },
        "/class": {
            "get": {
                "description": "get Class data in Db.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "class"
                ],
                "summary": "get Class",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "classid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.userResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create Class data in Db.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "class"
                ],
                "summary": "Create Class",
                "parameters": [
                    {
                        "description": "Create class",
                        "name": "class",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.createClassRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.classResponse"
                        }
                    }
                }
            }
        },
        "/classCatalogue": {
            "get": {
                "description": "get ClassCatalogue data in Db.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "classCatalogue"
                ],
                "summary": "get ClassCatalogue",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "userid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.classCatalogueResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create ClassCatalogue data in Db.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "classCatalogue"
                ],
                "summary": "Create ClassCatalogue",
                "parameters": [
                    {
                        "description": "Create ClassCatalogue Activity",
                        "name": "ClassCatalogue",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.createClassCatalogueRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.classCatalogueResponse"
                        }
                    }
                }
            }
        },
        "/device": {
            "get": {
                "description": "Get Device data from Db.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device"
                ],
                "summary": "Get Device From ID",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "deviceid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.deviceResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create Device data in Db.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device"
                ],
                "summary": "Create Device",
                "parameters": [
                    {
                        "description": "Create Device",
                        "name": "device",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.createDeviceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.deviceResponse"
                        }
                    }
                }
            }
        },
        "/employee": {
            "get": {
                "description": "Get Employee data from Db.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "employee"
                ],
                "summary": "Get Employee From EmployeeName",
                "parameters": [
                    {
                        "type": "string",
                        "name": "employeename",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.userResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create Employee data in Db.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "employee"
                ],
                "summary": "Create Employee",
                "parameters": [
                    {
                        "description": "Create employee",
                        "name": "employee",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.createEmployeeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.employeeResponse"
                        }
                    }
                }
            }
        },
        "/location": {
            "get": {
                "description": "Get User data from Db.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "location"
                ],
                "summary": "Get Location From ID",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "locationid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.locationResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create Location data in Db.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "location"
                ],
                "summary": "Create Location",
                "parameters": [
                    {
                        "description": "Create Location",
                        "name": "users",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.createLocationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.locationResponse"
                        }
                    }
                }
            }
        },
        "/userActivity": {
            "get": {
                "description": "Get User Activity data from Db.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "userActivity"
                ],
                "summary": "Get User Activity From ID",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "userid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.userActivityResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create UserActivity data in Db.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "userActivity"
                ],
                "summary": "Create UserActivity",
                "parameters": [
                    {
                        "description": "Create Device",
                        "name": "device",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.createUserActivityRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.userActivityResponse"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "Get User data from Db.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Get User From UserName",
                "parameters": [
                    {
                        "type": "string",
                        "name": "username",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.userResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create User data in Db.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Create User",
                "parameters": [
                    {
                        "description": "Create user",
                        "name": "users",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.createUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.userResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.checkinActivityResponse": {
            "type": "object",
            "properties": {
                "checkin": {
                    "type": "string"
                },
                "checkout": {
                    "type": "string"
                },
                "employeeid": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "locationid": {
                    "type": "integer"
                },
                "userid": {
                    "type": "integer"
                }
            }
        },
        "api.classCatalogueResponse": {
            "type": "object",
            "properties": {
                "courseid": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "userid": {
                    "type": "integer"
                }
            }
        },
        "api.classResponse": {
            "type": "object",
            "properties": {
                "classtype": {
                    "description": "weekly daily or monthly",
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "end_time": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "instructorid": {
                    "type": "integer"
                },
                "locationid": {
                    "type": "integer"
                },
                "reg_status": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                }
            }
        },
        "api.createCheckinActivityRequest": {
            "type": "object",
            "required": [
                "checkin",
                "checkout",
                "employeeid",
                "locationid",
                "userid"
            ],
            "properties": {
                "checkin": {
                    "type": "string"
                },
                "checkout": {
                    "type": "string"
                },
                "employeeid": {
                    "type": "integer"
                },
                "locationid": {
                    "type": "integer"
                },
                "userid": {
                    "type": "integer"
                }
            }
        },
        "api.createClassCatalogueRequest": {
            "type": "object",
            "required": [
                "courseid",
                "userid"
            ],
            "properties": {
                "courseid": {
                    "type": "integer"
                },
                "userid": {
                    "type": "integer"
                }
            }
        },
        "api.createClassRequest": {
            "type": "object",
            "required": [
                "classtype",
                "description",
                "end_time",
                "instructorid",
                "locationid",
                "reg_status",
                "start_time"
            ],
            "properties": {
                "classtype": {
                    "description": "weekly daily or monthly",
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "end_time": {
                    "type": "string"
                },
                "instructorid": {
                    "type": "integer"
                },
                "locationid": {
                    "type": "integer"
                },
                "reg_status": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                }
            }
        },
        "api.createDeviceRequest": {
            "type": "object",
            "required": [
                "description"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "status": {
                    "description": "Free,busy,not working",
                    "type": "string"
                }
            }
        },
        "api.createEmployeeRequest": {
            "type": "object",
            "required": [
                "email",
                "locationid",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "locationid": {
                    "type": "integer"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "api.createLocationRequest": {
            "type": "object",
            "required": [
                "city",
                "state",
                "zipcode"
            ],
            "properties": {
                "city": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "zipcode": {
                    "type": "string"
                }
            }
        },
        "api.createUserActivityRequest": {
            "type": "object",
            "required": [
                "deviceid",
                "end",
                "start",
                "userid"
            ],
            "properties": {
                "deviceid": {
                    "type": "integer"
                },
                "end": {
                    "type": "string"
                },
                "start": {
                    "type": "string"
                },
                "userid": {
                    "type": "integer"
                }
            }
        },
        "api.createUserRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "api.deviceResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "status": {
                    "description": "Free,busy,not working",
                    "type": "string"
                }
            }
        },
        "api.employeeResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "employeename": {
                    "type": "string"
                },
                "locationid": {
                    "type": "integer"
                }
            }
        },
        "api.locationResponse": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "state": {
                    "type": "string"
                },
                "zipcode": {
                    "type": "string"
                }
            }
        },
        "api.userActivityResponse": {
            "type": "object",
            "properties": {
                "deviceid": {
                    "type": "integer"
                },
                "end": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "start": {
                    "type": "string"
                },
                "userid": {
                    "type": "integer"
                }
            }
        },
        "api.userResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "0.0.0.0:8080",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Gym-backend API",
	Description:      "Gym-backend API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
